require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/spaces", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Space. As you add validations to Space, be sure to
  # adjust the attributes here as well.
  let(:tenant) { create(:tenant) }
  let(:user) { create(:user) }

  let(:valid_attributes) {
    { name: "Chatter", tenant: tenant, created_by: user }
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  before do
    sign_in user
  end


  describe "GET /index" do
    it "renders a successful response" do
      Space.create! valid_attributes
      get tenant_spaces_url(tenant.id)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      space = Space.create! valid_attributes
      get tenant_space_url(tenant.id, space)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tenant_space_url(tenant.id)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      space = Space.create! valid_attributes
      get edit_tenant_space_url(tenant.id, space)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Space" do
        expect {
          post tenant_spaces_url(tenant.id), params: { space: valid_attributes }
        }.to change(Space, :count).by(1)
      end

      it "redirects to the created space" do
        post tenant_spaces_url(tenant.id), params: { space: valid_attributes }
        expect(response).to redirect_to(tenant_space_url(tenant.id, Space.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Space" do
        expect {
          post tenant_spaces_url(tenant.id), params: { space: invalid_attributes }
        }.to change(Space, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tenant_spaces_url(tenant.id), params: { space: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "my new little name" }
      }

      it "updates the requested space" do
        space = Space.create! valid_attributes
        patch tenant_space_url(tenant.id, space), params: { space: new_attributes }
        space.reload

        expect(space.name).to eq "my new little name"
      end

      it "redirects to the space" do
        space = Space.create! valid_attributes
        patch tenant_space_url(tenant.id, space), params: { space: new_attributes }
        space.reload

        expect(response).to redirect_to(tenant_space_url(tenant, space))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        space = Space.create! valid_attributes
        patch tenant_space_url(tenant, space), params: { space: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested space" do
      space = Space.create! valid_attributes
      expect {
        delete tenant_space_url(tenant, space)
      }.to change(Space, :count).by(-1)
    end

    it "redirects to the spaces list" do
      space = Space.create! valid_attributes
      delete tenant_space_url(tenant, space)
      expect(response).to redirect_to(tenant_spaces_url(tenant))
    end
  end
end
